@startuml si1.3-update-user-password
title SI1.3 Update user password

start
:Receive password update request;

if (password update request valid?) then ([Yes])
  :Load user account;
  if (user account found?) then ([Yes])
    :Hash password;
    :Store password credential;
    if (later password change?) then ([Yes])
      :Invalidate other active sessions;
    endif
    :Produce business event
User password updated; <<sendSignal>>
    :Return success;
    stop
  else ([No])
    :Return account-not-found failure;
    stop
  endif
else ([No])
  :Return password validation failure
(invalid-request or password-policy);
  stop
endif

@enduml
