@startuml si1.2-confirm-user-email
title SI1.2 Confirm user email

start
:Receive email confirmation request;

if (confirmation token exists?) then ([Yes])
  if (confirmation token belongs to already-confirmed account?) then ([Yes])
    :Return success;
    stop
  else ([No])
    if (confirmation token expired?) then ([No])
      if (confirmation token unused?) then ([Yes])
        :Load unconfirmed user account;
        if (unconfirmed user account found?) then ([Yes])
          :Mark email as confirmed;
          :Invalidate confirmation token;
          :Produce business event
User email confirmed; <<sendSignal>>
          :Return success;
          stop
        else ([No])
          :Return confirmation failure;
          stop
        endif
      else ([No])
        :Return confirmation failure;
        stop
      endif
    else ([Yes])
      :Return confirmation failure;
      stop
    endif
  endif
else ([No])
  :Return confirmation failure;
  stop
endif

@enduml
