@startuml si4.1-create-backoffice-task
title SI4.1 Create backoffice task

start
:Consume event
backoffice-work business event; <<acceptEvent>>

if (backoffice task request valid?) then ([Yes])
  :Create backoffice task;
  :Queue task in provider or
backoffice work pile;
  :Produce business event
Backoffice task created; <<sendSignal>>
  stop
else ([No])
  :Nack event to DLQ <<sendSignal>>
task validation failure
(unsupported-task-type, subject-not-found,
or duplicate-task);
  stop
endif

@enduml
