@startuml si1.2-confirm-user-email
title SI1.2 Confirm user email

start
:Receive email confirmation request;

if (confirmation token exists?) then ([Yes])
  if (confirmation token expired?) then ([No])
    if (confirmation token unused?) then ([Yes])
      :Load unconfirmed user account;
      if (unconfirmed user account found?) then ([Yes])
        :Mark email as confirmed;
        :Invalidate confirmation token;
        :Produce business event
User email confirmed; <<sendSignal>>
        :Return success;
        stop
      else ([No])
        :Return account-not-found failure;
        stop
      endif
    else ([No])
      :Return used-token failure;
      stop
    endif
  else ([Yes])
    :Return expired-token failure;
    stop
  endif
else ([No])
  :Return invalid-token failure;
  stop
endif

@enduml
