@startuml si1.1-register-account
title SI1.1 Register account

start
:Receive registration request;

if (email valid?) then ([Yes])
  if (user exists?) then ([Yes])
    :Return user-exists failure;
    stop
  else ([No])
    :Create user account in unconfirmed state;
    :Create email confirmation token;
    :Produce business event
preliminaryUserCreated;
    :Return registration accepted;
    stop
  endif
else ([No])
  :Return invalid-email failure;
  stop
endif

@enduml
