@startuml si1.3-update-user-password
title SI1.3 Update user password

start
:Receive password update request;

if (request context valid?) then ([Yes])
  if (password satisfies policy?) then ([Yes])
    :Load user account;
    if (user account found?) then ([Yes])
      :Hash password;
      :Store password credential;
      :Produce business event
User password updated; <<sendSignal>>
      :Return success;
      stop
    else ([No])
      :Return account-not-found failure;
      stop
    endif
  else ([No])
    :Return password-policy failure;
    stop
  endif
else ([No])
  :Return invalid-request failure;
  stop
endif

@enduml
