@startuml si1.7-resolve-pending-registration
title SI1.7 Resolve pending registration

start
:Receive pending registration resolution request;

if (pending registration resolution valid?) then ([Yes])
  if (is acceptance?) then ([Yes])
    :Create registered equipment;
    :Mark registration as accepted;
    :Produce business event
Equipment registration accepted; <<sendSignal>>
  else ([No, rejection])
    :Store rejection reason if provided;
    :Mark registration as rejected;
    :Produce business event
Equipment registration rejected; <<sendSignal>>
  endif
  :Return success;
  stop
else ([No])
  :Return registration resolution failure
(invalid-decision, registration-not-found,
or already-resolved);
  stop
endif

@enduml
