@startuml si2.4-initiate-esigning-for-maintenance-plan
title SI2.4 Initiate eSigning for maintenance plan

start
:Consume event
Maintenance plan request approved; <<acceptEvent>>

if (pending maintenance plan can be signed?) then ([Yes])
  :Load pending maintenance plan;
  :Mark plan approved pending signature;
  :Generate maintenance plan agreement;
  :Request customer signature; <<sendCommand>>
  if (eSigning request accepted?) then ([Yes])
    :Store signature order reference;
    :Produce business event
Maintenance plan signature requested; <<sendSignal>>
    stop
  else ([No])
    :Nack event to DLQ <<sendSignal>>
esigning-request-failed failure;
    stop
  endif
else ([No])
  :Nack event to DLQ <<sendSignal>>
signing validation failure
(plan-not-found, plan-not-approved,
or customer-not-signable);
  stop
endif

@enduml
