@startuml si3.6-accept-maintenance-slots-proposal
title SI3.6 Accept maintenance slots proposal

start
:Receive selected maintenance slot request;

:Load maintenance slots proposal;
if (proposal found?) then ([Yes])
  if (proposal selectable?) then ([Yes])
    if (selected slot belongs to proposal?) then ([Yes])
      if (selected slot still available?) then ([Yes])
        :Remove reserved slots from proposal;
        :Schedule accepted maintenance slot;
        :Produce business event
Maintenance job scheduled; <<sendSignal>>
        :Return scheduled maintenance slot;
        stop
      else ([No])
        :Return selected-slot-unavailable failure;
        stop
      endif
    else ([No])
      :Return selected-slot-not-in-proposal failure;
      stop
    endif
  else ([No])
    :Return proposal-not-selectable failure;
    stop
  endif
else ([No])
  :Return proposal-not-found failure;
  stop
endif

@enduml
