@startuml si3.5-cancel-maintenance-job
title SI3.5 Cancel maintenance job

start
:Receive maintenance job cancellation request;

:Load scheduled maintenance job;
if (scheduled maintenance job found?) then ([Yes])
  if (job scheduled?) then ([Yes])
    if (cancellation rules allow cancellation?) then ([Yes])
      :Mark job as cancelled;
      :Create backoffice task to notify provider;
      :Produce business event
Maintenance job cancelled;
      :Produce business event
Maintenance provider cancellation task created;
      :Return success;
      stop
    else ([No])
      :Return cancellation-not-allowed failure;
      stop
    endif
  else ([No])
    :Return job-not-scheduled failure;
    stop
  endif
else ([No])
  :Return job-not-found failure;
  stop
endif

@enduml
