@startuml si4.1-create-backoffice-review-task
title SI4.1 Create backoffice task

start
:Consume business event
Backoffice work requested;

if (task subject and type valid?) then ([Yes])
  :Create backoffice task;
  :Assign or queue task for backoffice worker;
  :Produce business event
Backoffice task created;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
