@startuml si1.7-accept-registration
title SI1.7 Accept registration

start
:Receive accept registration command;

if (pending registration can be accepted?) then ([Yes])
  :Load pending registration;
  :Create or activate registered equipment;
  :Mark registration as accepted;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
