@startuml si1.5-create-pending-registration
title SI1.5 Create pending registration

start
:Consume business event
Equipment registration submitted;

if (customer and equipment data valid?) then ([Yes])
  :Create pending equipment registration;
  :Produce business event
Pending equipment registration created;
  :Return pending registration;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
