@startuml si1.3-update-user-password
title SI1.3 Update user password

start
:Consume business event
User password submitted;

if (request and password valid?) then ([Yes])
  :Load user account;
  :Hash password;
  :Store password credential;
  :Produce business event
User password updated;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
