@startuml si1.2-confirm-user-email
title SI1.2 Confirm user email

start
:Consume business event
Email confirmation requested;

if (confirmation token valid?) then ([Yes])
  :Load unconfirmed user account;
  :Mark email as confirmed;
  :Invalidate confirmation token;
  :Produce business event
User email confirmed;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
