@startuml si1.4-set-user-preferences
title SI1.4 Set user preferences

start
:Consume business event
User preferences submitted;

if (preferences valid?) then ([Yes])
  :Load user profile;
  :Store name and address preferences;
  :Produce business event
User preferences set;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
