@startuml si2.4-notify-customer-of-accepted-registration
title SI2.4 Notify customer of accepted registration

start
:Receive accepted registration event;

if (event valid?) then ([Yes])
  :Load customer and accepted registration;
  :Render accepted registration notification;
  :Send notification to customer;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
