@startuml si3.6-accept-maintenance-slots-proposal
title SI3.6 Accept maintenance slots proposal

start
:Consume business event
Maintenance slot selected;

if (proposal and selected slot valid?) then ([Yes])
  :Load maintenance slots proposal;
  :Remove reserved slots from proposal;
  :Schedule accepted maintenance slot;
  :Produce business event
Maintenance job scheduled;
  :Return scheduled maintenance slot;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
