@startuml si3.5-cancel-maintenance-job
title SI3.5 Cancel maintenance job

start
:Receive cancel maintenance job request;

if (scheduled maintenance job can be cancelled?) then ([Yes])
  :Load scheduled maintenance job;
  :Mark job as cancelled;
  :Create backoffice task to notify provider;
  :Return success;
  stop
else ([No])
  :Return failure;
  stop
endif

@enduml
